-- 硫化班次配置表（按工厂维护排程窗口内班次序列，1≤N≤8；无数据时程序使用默认 8 班模板）
CREATE TABLE `T_LH_SHIFT_CONFIG` (
  `ID` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `FACTORY_CODE` varchar(64) DEFAULT NULL COMMENT '工厂编号',
  `SHIFT_CODE` varchar(64) DEFAULT NULL COMMENT '班次编号',
  `SHIFT_NAME` varchar(128) DEFAULT NULL COMMENT '班次名称（如：T日早班、T+1日夜班等）',
  `SHIFT_INDEX` int DEFAULT NULL COMMENT '班次序号/索引（1~N，对应class1到classN）',
  `SHIFT_TYPE` varchar(32) DEFAULT NULL COMMENT '班次类型（早班/中班/夜班，或枚举编码01/02/03）',
  `WORK_DATE` datetime DEFAULT NULL COMMENT '所属日期（业务上T日、T+1日等的日历日，一般取当日0点）',
  `START_TIME` datetime DEFAULT NULL COMMENT '班次开始时间（取时刻；与DATE_OFFSET配合）',
  `END_TIME` datetime DEFAULT NULL COMMENT '班次结束时间（取时刻；跨日班结束时刻在次日）',
  `DATE_OFFSET` int DEFAULT NULL COMMENT '日期偏移（0表示T日，1表示T+1，2表示T+2）',
  `SHIFT_DURATION` int DEFAULT NULL COMMENT '班次时长（小时）',
  `REMARK` varchar(512) DEFAULT NULL COMMENT '备注',
  `IS_DELETE` int DEFAULT 0 COMMENT '删除标志：0-未删除 1-已删除',
  `CREATE_BY` varchar(64) DEFAULT NULL COMMENT '创建者',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_BY` varchar(64) DEFAULT NULL COMMENT '更新者',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_FACTORY_DELETE` (`FACTORY_CODE`,`IS_DELETE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='硫化班次配置表';

-- 若库中仍为旧列 SHIFT_MINUTES（分钟），可迁移为小时列（请先备份并按业务换算或清空后重灌数据）：
-- ALTER TABLE T_LH_SHIFT_CONFIG DROP COLUMN SHIFT_MINUTES;
-- ALTER TABLE T_LH_SHIFT_CONFIG ADD COLUMN SHIFT_DURATION int DEFAULT NULL COMMENT '班次时长（小时）' AFTER DATE_OFFSET;
-- 若列名为 SHIFT_DURATION_HOURS，可重命名：ALTER TABLE T_LH_SHIFT_CONFIG CHANGE SHIFT_DURATION_HOURS SHIFT_DURATION int DEFAULT NULL COMMENT '班次时长（小时）';
