SELECT ID, MACHINE_CODE, STATUS, IS_DELETE, UPDATE_BY, UPDATE_TIME
FROM t_lh_machine_info
WHERE ID=17188;

SELECT ID, ONLINE_DATE, LH_CODE, MATERIAL_CODE, MES_MATERIAL_CODE, REMARK
FROM t_lh_machine_online_info
WHERE ID IN (32129410,32129411)
ORDER BY ID;

SELECT ID, MATERIAL_CODE, DAY_1, DAY_2, DAY_3, TOTAL_QTY, DIFFERENCE_QTY
FROM t_mp_month_plan_prod_final
WHERE ID=703943;

SELECT ID, FACTORY_CODE, MATERIAL_CODE, CLASS_CAPACITY, STANDARD_CAPACITY, APS_CAPACITY, IS_DELETE
FROM t_mdm_sku_lh_capacity
WHERE MATERIAL_CODE='3302001513'
ORDER BY ID;
