; 数据库连接配置文件
; 使用方式：
;   python execute_sql_batch.py --config db_config.ini --section dev
;   python export_mysql_sql.py --config db_config.ini --section test

[dev]
host = 127.0.0.1
port = 3307
user = root
password = 123456
database = apslh
charset = utf8mb4

[test]
host = 192.168.2.124
port = 3306
user = root
password = neW46Ik#Gq@
database = jy_aps
charset = utf8mb4

[uat]
host = 172.21.7.130
port = 3306
user = tbr_aps
password = NahPDzeShSxA%
database = jy_aps
charset = utf8mb4
